actor_init_w: 0.001
actor_ln: false
actor_lr: 0.0001
algo_type: SPOT
batch_size: 256
beta: 0.5
buffer_size: 2000000
checkpoints_path: null
critic_init_w: 0.003
critic_ln: false
critic_lr: 0.0003
device: cuda
discount: 0.99
env: antmaze-large-diverse-v2
eval_freq: 10000
eval_seed: 0
expl_noise: 0.1
group: OPT-D4RL
iwae: false
kappa: 0.1
kappa_cool: 200000
kappa_end: 0.9
lambd: 0.025
lambd_cool: true
lambd_end: 0.2
load_model: ''
N_pretrain: 50000
N_tau: 25000
n_episodes: 100
name: OPT
noise_clip: 0.5
normalize: false
normalize_reward: true
num_samples: 1
offline_iterations: 1000000
online_discount: 0.995
online_iterations: 1000000
policy_freq: 2
policy_noise: 0.2
project: OPT
seed: 0
tau: 0.005
temperature: 5
UTD_ratio: 1
vae_hidden_dim: 750
vae_iterations: 100000
vae_latent_dim: null
vae_lr: 0.001