actor_init_w: null
actor_ln: false
actor_lr: 0.0003
algo_type: TD3
batch_size: 256
buffer_size: 2000000
checkpoints_path: null
critic_init_w: null
critic_ln: false
critic_lr: 0.0003
device: cuda
discount: 0.99
env: walker2d-medium-replay-v2
eval_freq: 5000
eval_seed: 0
expl_noise: 0.1
group: OPT-D4RL
kappa: 0
kappa_cool: 150000
kappa_end: 1
load_model: ''
N_pretrain: 50000
N_tau: 25000
n_episodes: 10
name: OPT
noise_clip: 0.5
normalize: false
normalize_reward: false
offline_iterations: 1000000
online_iterations: 1000000
policy_freq: 2
policy_noise: 0.2
project: OPT
seed: 0
tau: 0.005
temperature: 5
UTD_ratio: 5